### ISSUE TITLE
launching on catalina with graphics doesn't work

### ISSUE THREAD

**Issue by schluppeck** [schluppeck/dockerize-analysis#1]
came across the following error today after the `docker run` with the `-e DISPLAY:host.docker.internal:0` working fine for a while:

```bash
neuro@0e1660e599e7:~/nipype_tutorial$ fsl &
 [1] 40
neuro@0e1660e599e7:~/nipype_tutorial$ 
 application-specific initialization failed: couldn't connect to display "host.docker.internal:0"
```
It turns out this is an authentication issue (`xhost +` required on local machine, as per the following blog post

https://medium.com/@mreichelt/how-to-show-x11-windows-within-docker-on-mac-50759f4b65cb

after this fix, things work (again):

<img width="805" alt="Screenshot 2020-10-15 at 20 16 22" src="https://user-images.githubusercontent.com/10121356/96175835-5c323b80-0f23-11eb-86b6-2fb7fbf0005a.png">

**Comment by schluppeck** [comment]
@ryanelson1996 - just putting this here, as this is the thing that broke quick demo today... may not be an issue under Windows/Docker Desktop + some X client there, but let me know if there is similar problems there.

**Comment by ryanelson1996** [comment]
Thanks @schluppeck I'll let you know how I get on and whether I run into any problems like this.
